version: '3.8'

services:
  klippers-fastapi-app:
    container_name: klippers-fastapi-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "23081:22081"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://qsignuser:qsign_qazwsxqazwsx@klippers-postgres-db:5432/qsign_test
    restart: unless-stopped
    depends_on:
      - klippers_postgres_db
    networks:
      - app_network
  klippers-nodejs-app:
    container_name: klippers-nodejs-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "23080:22080"
      - "23043:22443"
    environment:
      POSTGRES_USER: qsignuser
      POSTGRES_PASSWORD: qsign_qazwsxqazwsx
      POSTGRES_DB: qsign_test
    networks:
      - app_network


  klippers_postgres_db:
    container_name: klippers-postgres-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: qsignuser
      POSTGRES_PASSWORD: qsign_qazwsxqazwsx
      POSTGRES_DB: qsign_test
    volumes:
      - klippers_postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


volumes:
  klippers_postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge 
