/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
 */
export interface BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost {
    /**
     * ID of the signer
     * @type {string}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    signerId: string;
    /**
     * Page number where signature should be placed
     * @type {number}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    page: number;
    /**
     * X coordinate of signature placement
     * @type {number}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    x: number;
    /**
     * Y coordinate of signature placement
     * @type {number}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    y: number;
    /**
     * Width of signature area
     * @type {number}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    width: number;
    /**
     * Height of signature area
     * @type {number}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    height: number;
    /**
     * Base64 encoded signature image (optional)
     * @type {string}
     * @memberof BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost
     */
    signatureImageBase64?: string;
}

/**
 * Check if a given object implements the BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost interface.
 */
export function instanceOfBodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost(value: object): value is BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost {
    if (!('signerId' in value) || value['signerId'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostFromJSON(json: any): BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost {
    return BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostFromJSONTyped(json, false);
}

export function BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost {
    if (json == null) {
        return json;
    }
    return {
        
        'signerId': json['signer_id'],
        'page': json['page'],
        'x': json['x'],
        'y': json['y'],
        'width': json['width'],
        'height': json['height'],
        'signatureImageBase64': json['signature_image_base64'] == null ? undefined : json['signature_image_base64'],
    };
}

export function BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostToJSON(json: any): BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost {
    return BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostToJSONTyped(json, false);
}

export function BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPostToJSONTyped(value?: BodyCreateSignatureInPdfApiV1DocumentsPdfFilesPdfFileIdSignaturesPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signer_id': value['signerId'],
        'page': value['page'],
        'x': value['x'],
        'y': value['y'],
        'width': value['width'],
        'height': value['height'],
        'signature_image_base64': value['signatureImageBase64'],
    };
}

