/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCreateSignerApiV1DocumentsDocumentIdSignersPost
 */
export interface BodyCreateSignerApiV1DocumentsDocumentIdSignersPost {
    /**
     * Email address of the signer
     * @type {string}
     * @memberof BodyCreateSignerApiV1DocumentsDocumentIdSignersPost
     */
    email: string;
    /**
     * Name of the signer
     * @type {string}
     * @memberof BodyCreateSignerApiV1DocumentsDocumentIdSignersPost
     */
    name: string;
    /**
     * Order in which the signer should sign (1, 2, 3, etc.)
     * @type {number}
     * @memberof BodyCreateSignerApiV1DocumentsDocumentIdSignersPost
     */
    order: number;
}

/**
 * Check if a given object implements the BodyCreateSignerApiV1DocumentsDocumentIdSignersPost interface.
 */
export function instanceOfBodyCreateSignerApiV1DocumentsDocumentIdSignersPost(value: object): value is BodyCreateSignerApiV1DocumentsDocumentIdSignersPost {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function BodyCreateSignerApiV1DocumentsDocumentIdSignersPostFromJSON(json: any): BodyCreateSignerApiV1DocumentsDocumentIdSignersPost {
    return BodyCreateSignerApiV1DocumentsDocumentIdSignersPostFromJSONTyped(json, false);
}

export function BodyCreateSignerApiV1DocumentsDocumentIdSignersPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateSignerApiV1DocumentsDocumentIdSignersPost {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'order': json['order'],
    };
}

export function BodyCreateSignerApiV1DocumentsDocumentIdSignersPostToJSON(json: any): BodyCreateSignerApiV1DocumentsDocumentIdSignersPost {
    return BodyCreateSignerApiV1DocumentsDocumentIdSignersPostToJSONTyped(json, false);
}

export function BodyCreateSignerApiV1DocumentsDocumentIdSignersPostToJSONTyped(value?: BodyCreateSignerApiV1DocumentsDocumentIdSignersPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'order': value['order'],
    };
}

