/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut
 */
export interface BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut {
    /**
     * New status for the session
     * @type {string}
     * @memberof BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut
     */
    completedAt?: Date | null;
}

/**
 * Check if a given object implements the BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut interface.
 */
export function instanceOfBodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut(value: object): value is BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutFromJSON(json: any): BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut {
    return BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutFromJSONTyped(json, false);
}

export function BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
    };
}

export function BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutToJSON(json: any): BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut {
    return BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutToJSONTyped(json, false);
}

export function BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPutToJSONTyped(value?: BodyUpdateSigningSessionApiV1DocumentsSigningSessionsSessionIdPut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
    };
}

