/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost
 */
export interface BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost {
    /**
     * Expiration date and time for the session
     * @type {Date}
     * @memberof BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost
     */
    expiresAt: Date;
    /**
     * Initial status of the signing session
     * @type {string}
     * @memberof BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost
     */
    status?: string;
    /**
     * Email of the signer for this session
     * @type {string}
     * @memberof BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost
     */
    signerEmail: string;
}

/**
 * Check if a given object implements the BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost interface.
 */
export function instanceOfBodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost(value: object): value is BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('signerEmail' in value) || value['signerEmail'] === undefined) return false;
    return true;
}

export function BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostFromJSON(json: any): BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost {
    return BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostFromJSONTyped(json, false);
}

export function BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': (new Date(json['expires_at'])),
        'status': json['status'] == null ? undefined : json['status'],
        'signerEmail': json['signer_email'],
    };
}

export function BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostToJSON(json: any): BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost {
    return BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostToJSONTyped(json, false);
}

export function BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPostToJSONTyped(value?: BodyCreateSigningSessionApiV1DocumentsDocumentIdSigningSessionsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': ((value['expiresAt']).toISOString()),
        'status': value['status'],
        'signer_email': value['signerEmail'],
    };
}

