/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
 */
export interface BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost {
    /**
     * ID of the signer
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    signerId: string;
    /**
     * Email of the signer
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    signerEmail: string;
    /**
     * Name of the signer
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    signerName: string;
    /**
     * Action performed (e.g., 'VIEWED', 'SIGNED')
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    action: string;
    /**
     * IP address of the signer
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    ipAddress: string;
    /**
     * User agent of the signer's browser
     * @type {string}
     * @memberof BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost
     */
    userAgent: string;
}

/**
 * Check if a given object implements the BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost interface.
 */
export function instanceOfBodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost(value: object): value is BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost {
    if (!('signerId' in value) || value['signerId'] === undefined) return false;
    if (!('signerEmail' in value) || value['signerEmail'] === undefined) return false;
    if (!('signerName' in value) || value['signerName'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('userAgent' in value) || value['userAgent'] === undefined) return false;
    return true;
}

export function BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostFromJSON(json: any): BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost {
    return BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostFromJSONTyped(json, false);
}

export function BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'signerId': json['signer_id'],
        'signerEmail': json['signer_email'],
        'signerName': json['signer_name'],
        'action': json['action'],
        'ipAddress': json['ip_address'],
        'userAgent': json['user_agent'],
    };
}

export function BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostToJSON(json: any): BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost {
    return BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostToJSONTyped(json, false);
}

export function BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPostToJSONTyped(value?: BodyCreateSignatureAuditApiV1DocumentsDocumentIdSignatureAuditsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signer_id': value['signerId'],
        'signer_email': value['signerEmail'],
        'signer_name': value['signerName'],
        'action': value['action'],
        'ip_address': value['ipAddress'],
        'user_agent': value['userAgent'],
    };
}

