/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyUpdateDocumentApiV1DocumentsDocumentIdPost
 */
export interface BodyUpdateDocumentApiV1DocumentsDocumentIdPost {
    /**
     * 
     * @type {string}
     * @memberof BodyUpdateDocumentApiV1DocumentsDocumentIdPost
     */
    status?: string | null;
    /**
     * 
     * @type {object}
     * @memberof BodyUpdateDocumentApiV1DocumentsDocumentIdPost
     */
    metaData?: object | null;
}

/**
 * Check if a given object implements the BodyUpdateDocumentApiV1DocumentsDocumentIdPost interface.
 */
export function instanceOfBodyUpdateDocumentApiV1DocumentsDocumentIdPost(value: object): value is BodyUpdateDocumentApiV1DocumentsDocumentIdPost {
    return true;
}

export function BodyUpdateDocumentApiV1DocumentsDocumentIdPostFromJSON(json: any): BodyUpdateDocumentApiV1DocumentsDocumentIdPost {
    return BodyUpdateDocumentApiV1DocumentsDocumentIdPostFromJSONTyped(json, false);
}

export function BodyUpdateDocumentApiV1DocumentsDocumentIdPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyUpdateDocumentApiV1DocumentsDocumentIdPost {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'metaData': json['meta_data'] == null ? undefined : json['meta_data'],
    };
}

export function BodyUpdateDocumentApiV1DocumentsDocumentIdPostToJSON(json: any): BodyUpdateDocumentApiV1DocumentsDocumentIdPost {
    return BodyUpdateDocumentApiV1DocumentsDocumentIdPostToJSONTyped(json, false);
}

export function BodyUpdateDocumentApiV1DocumentsDocumentIdPostToJSONTyped(value?: BodyUpdateDocumentApiV1DocumentsDocumentIdPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta_data': value['metaData'],
    };
}

