/* tslint:disable */
/* eslint-disable */
/**
 * OXSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PDFFileBase64
 */
export interface PDFFileBase64 {
    /**
     * 
     * @type {string}
     * @memberof PDFFileBase64
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PDFFileBase64
     */
    documentId: string;
    /**
     * 
     * @type {string}
     * @memberof PDFFileBase64
     */
    fileDataBase64: string;
    /**
     * 
     * @type {number}
     * @memberof PDFFileBase64
     */
    fileSize: number;
    /**
     * 
     * @type {number}
     * @memberof PDFFileBase64
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof PDFFileBase64
     */
    uploadedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PDFFileBase64
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PDFFileBase64
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PDFFileBase64
     */
    md5Hash: string;
    /**
     * 
     * @type {object}
     * @memberof PDFFileBase64
     */
    metaData?: object;
}

/**
 * Check if a given object implements the PDFFileBase64 interface.
 */
export function instanceOfPDFFileBase64(value: object): value is PDFFileBase64 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('fileDataBase64' in value) || value['fileDataBase64'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    if (!('uploadedAt' in value) || value['uploadedAt'] === undefined) return false;
    if (!('md5Hash' in value) || value['md5Hash'] === undefined) return false;
    return true;
}

export function PDFFileBase64FromJSON(json: any): PDFFileBase64 {
    return PDFFileBase64FromJSONTyped(json, false);
}

export function PDFFileBase64FromJSONTyped(json: any, ignoreDiscriminator: boolean): PDFFileBase64 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'documentId': json['document_id'],
        'fileDataBase64': json['file_data_base64'],
        'fileSize': json['file_size'],
        'version': json['version'] == null ? undefined : json['version'],
        'uploadedAt': (new Date(json['uploaded_at'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'md5Hash': json['md5_hash'],
        'metaData': json['meta_data'] == null ? undefined : json['meta_data'],
    };
}

export function PDFFileBase64ToJSON(json: any): PDFFileBase64 {
    return PDFFileBase64ToJSONTyped(json, false);
}

export function PDFFileBase64ToJSONTyped(value?: PDFFileBase64 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'document_id': value['documentId'],
        'file_data_base64': value['fileDataBase64'],
        'file_size': value['fileSize'],
        'version': value['version'],
        'uploaded_at': ((value['uploadedAt']).toISOString()),
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'completed_at': value['completedAt'] == null ? undefined : ((value['completedAt'] as any).toISOString()),
        'md5_hash': value['md5Hash'],
        'meta_data': value['metaData'],
    };
}

